version: '3'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    command: ["anvil", "--host", "0.0.0.0"]

  bundler:
    build:
      context: .
      dockerfile: Dockerfile.bundler
    ports:
      - "${BUNDLER_PORT}:${BUNDLER_PORT}"
    command:
      ["yarn", "run", "bundler", "--unsafe", "--network", "http://node:${NODE_PORT}"]
    depends_on:
      - node
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BUNDLER_PORT}/"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  
  contracts:
    build:
      context: ./contracts
      dockerfile: Dockerfile
    environment:
      - NODE_URL=http://node:${NODE_PORT}
      - BUNDLER_URL=http://bundler:${BUNDLER_PORT}/rpc
    command: ["npx", "hardhat", "run", "scripts/deployEmailAccountFactory.ts", "--network", "dev"]
    depends_on:
      bundler:
        condition: service_healthy
  
  scanner:
    image: otterscan/otterscan:latest
    ports:
      - "${SCANNER_PORT}:80"

  smtp:
    build:
      context: .
      dockerfile: Dockerfile.smtp
    environment:
      - SERVER_HOST=${SMTP_INTERNAL_SERVER_HOST}
      - SERVER_PORT=${SMTP_INTERNAL_SERVER_PORT}
      - SMTP_DOMAIN_NAME=${SMTP_DOMAIN_NAME}
      - SMTP_LOGIN_ID=${SMTP_LOGIN_ID}   # IMAP login id - usually your email address.
      - SMTP_LOGIN_PASSWORD=${SMTP_LOGIN_PASSWORD}
      - MESSAGE_ID_DOMAIN=${SMTP_MESSAGE_ID_DOMAIN}
      - JSON_LOGGER=${SMPT_JSON_LOGGER}
    ports:
      - "${SMTP_PORT}:${SMTP_INTERNAL_SERVER_PORT}"
    command: ["./relayer-smtp"]

