services:
  node:
    image: ethereum/client-go:v1.13.5
    ports:
      - "${NODE_PORT}:8545"
    command: [
      "--miner.gaslimit", "12000000",
      "--http", "--http.api", "personal,eth,net,web3,debug",
      "--http.vhosts", "*,localhost,host.docker.internal", "--http.addr", "0.0.0.0",
      "--allow-insecure-unlock", "--rpc.allow-unprotected-txs",
      "--dev",
      "--verbosity", "2",
      "--nodiscover", "--maxpeers", "0", "--mine",
      "--networkid", "1337"
    ]

  bundler:
    build:
      context: .
      dockerfile: Dockerfile.bundler
    ports:
      - "${BUNDLER_PORT}:${BUNDLER_PORT}"
    command:
      ["yarn", "run", "bundler", "--network", "http://node:${NODE_PORT}"]
    depends_on:
      - node
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BUNDLER_PORT}/"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  
  contracts:
    build:
      context: ./contracts
      dockerfile: Dockerfile
    environment:
      - NODE_URL=http://node:${NODE_PORT}
      - BUNDLER_URL=http://bundler:${BUNDLER_PORT}/rpc
    command: ["/bin/sh", "-c", "npx hardhat run scripts/deploy/deployEmailAccountFactory.ts --network dev"]
    depends_on:
      bundler:
        condition: service_healthy
    volumes:
      - ./contracts/deployedAddresses:/usr/src/app/deployedAddresses  # Add this line to mount the volume
  
  scanner:
    image: otterscan/otterscan:latest
    ports:
      - "${SCANNER_PORT}:80"

  smtp:
    build:
      context: .
      dockerfile: Dockerfile.smtp
    environment:
      - SERVER_HOST=${SMTP_INTERNAL_SERVER_HOST}
      - SERVER_PORT=${SMTP_INTERNAL_SERVER_PORT}
      - SMTP_DOMAIN_NAME=${SMTP_DOMAIN_NAME}
      - SMTP_LOGIN_ID=${SMTP_LOGIN_ID}
      - SMTP_LOGIN_PASSWORD=${SMTP_LOGIN_PASSWORD}
      - MESSAGE_ID_DOMAIN=${SMTP_MESSAGE_ID_DOMAIN}
      - JSON_LOGGER=${SMPT_JSON_LOGGER}
    ports:
      - "${SMTP_PORT}:${SMTP_INTERNAL_SERVER_PORT}"
    command: ["relayer-smtp"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SMTP_INTERNAL_SERVER_PORT}/api/ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  imap:
    build:
      context: .
      dockerfile: Dockerfile.imap
    environment:
      - RELAYER_ENDPOINT=http://relayer:${RELAYER_PORT}/signAndSend
      - IMAP_LOGIN_ID=${IMAP_LOGIN_ID}
      - IMAP_LOGIN_PASSWORD=${IMAP_LOGIN_PASSWORD}
      - IMAP_DOMAIN_NAME=${IMAP_DOMAIN_NAME}
      - IMAP_PORT=${IMAP_PORT}
      - AUTH_TYPE=${IMAP_AUTH_TYPE}
      - JSON_LOGGER=${IMAP_JSON_LOGGER}
    command: ["relayer-imap"]
    depends_on:
      - relayer
  
  relayer:
    build:
      context: ./relayer
      dockerfile: Dockerfile
    ports:
      - "${RELAYER_PORT}:${RELAYER_PORT}"
    environment:
      - PORT=${RELAYER_PORT}
      - BUNDLER_URL=http://bundler:${BUNDLER_PORT}/rpc
    command: ["yarn", "start"]
