services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "8545:8545"
    command: ["anvil", "--host", "0.0.0.0"]

  bundler:
    build:
      context: .
      dockerfile: Dockerfile.bundler
    ports:
      - "3000:3000"
    command:
      ["yarn", "run", "bundler", "--unsafe", "--network", "http://node:8545"]
    depends_on:
      - node
